name: Validate Coins
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master, dev]

jobs:
  validate-coins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'   # safer than 14 (EOL)

      - name: Install JSON tools
        run: |
          sudo npm install -g json-diff
          sudo apt-get install jq -y

      - name: Install Python
        run: |
          sudo apt-get install python3 python3-pip -y
          pip3 install jsonlines requests

      - name: Get coins repo commit
        id: coins
        run: |
          echo "hash=$(jq -r .coins_repo_commit coins_ci.json)" >> $GITHUB_ENV
        shell: bash

      - name: Download coins.json and coins_config.json
        run: |
          set -e
          echo "Using commit $hash"
          curl -f -L -o coins.json https://raw.githubusercontent.com/KomodoPlatform/coins/${hash}/coins.json
          curl -f -L -o coins_config.json https://raw.githubusercontent.com/KomodoPlatform/coins/${hash}/utils/coins_config.json

      - name: Compare coins.json
        run: |
          json-diff assets/coins.json coins.json || true
          
      - name: Compare coins_config.json
        run: |
          json-diff assets/coins_config.json coins_config.json || true

      - name: Check wallet-only coins
        run: python3 utils/check_wallet_only.py

      - name: Check URLs in app_config.dart
        run: python3 utils/check_urls.py
